service: optimized-aws-sdk-layer

provider:
  name: aws
  runtime: nodejs10.x

layers:
  OptimizedAwsSdk:
    path: opt
    name: optimized-aws-sdk
    description: AWS-SDK v2.488.0
    licenseInfo: MIT
    compatibleRuntimes:
      - nodejs8.10
      - nodejs10.x
    allowedAccounts:
      - '*'
    retain: true